# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  cli: circleci/circleci-cli@volatile
  
jobs:
  build:
    executors:
      docker-php:
        docker:
          - image: cirrusci/flutter
      
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
      - run: flutter pub run flutter_coverage_badge
      - run: flutter pub get
      
      - run: git add .
      - run: git commit -m "coverage[skip ci]" 
      - run: git merge
      - run: git push origin main
#       - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

