# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  cli: circleci/circleci-cli@volatile
  node: circleci/node@5.0.2
  
jobs:
  build:
    docker:
      - image: 'circleci/node:10.0.0'
      - image: cirrusci/flutter
      
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
      - run: genhtml -o coverage coverage/lcov.info
      - run: flutter pub get
      - run: npm init -y
      - run: npm install lcov2badge
      - run: npm run just
      
      - run: git add .
      - run: git commit -m "coverage[skip ci]" 
      - run: git merge
      - run: git push origin main
#       - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

